import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans as IBMPlexSans } from "next/font/google";
import "./globals.css";
import React from "react";

import NextAuthProvider from "@/components/NextAuthProvider";
import { ThemeProvider } from "@/context/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const ibmPlexSans = IBMPlexSans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${ibmPlexSans.className}`}>
        <div className="flex size-full min-h-screen flex-col justify-between">
          <main className="mx-auto w-full flex-auto">
            <NextAuthProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </NextAuthProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
